---
# tasks file for Patroni
- name: Copy patroni
  copy:
    src: patroni-2.1.3-1.el7.x86_64.rpm
    dest: /tmp
  tags: install_patroni

- name: Install patroni rpm
  yum:
    name:
      - /tmp/patroni-2.1.3-1.el7.x86_64.rpm
      - patroni-consul
    disable_gpg_check: yes
    state: present
  tags: install_patroni

- name: Change ownership of a directory
  ansible.builtin.file:
    path: 
    - '{{ item }}'
    state: directory
    owner: postgres
    group: postgres
    mode: '700'
  loop:
    - /pgsql
    - {{ path_postgres_data }}
    - {{ path_postgres_wal }}
  tags: chown_dir

       